### ISSUE TITLE
신혼에 왠 리파지토리...

### ISSUE THREAD

**Issue by trainto** [jojiiiiyoung/gatsby#1]
신혼이나 즐기지 뭔 gatsby 해보겠다고 repo.를 파고 있나......

**Comment by jojiiiiyoung** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ왜 이슈를 오픈하고 그래여!!ㅋㅋㅋ 이거 회사에서 발표한다고..........또르륵

**Comment by trainto** [comment]
정적페이지 생성은 요즘은 gatsby 보다 next 가 나아 보이는데... ㅋㅋㅋㅋ 발표 잘 하시고~ 이슈는 close 하겠습니다.
